Develop
villigo/praktikum-12 pull request #1
Opened 2020-01-23 19:24 UTC by villigo

Подготовил проект на ревью.

2020-01-23 21:05 UTC, zhukovalexey76 requested changes
Есть несколько моментов требующих доработки.

#### Надо исправить

1) Пара проблем в `router.get('/users/:id`. Подробнее в комментариях к коду.

2) Ошибки линтинга

    ```text
    $ eslint . --ext .js
    
    /home/alex/code-review/PCR-9290/app.js
      11:9   error    Unexpected function expression             prefer-arrow-callback
      11:9   warning  Unexpected unnamed function                func-names
      11:17  error    Missing space before function parentheses  space-before-function-paren
      11:28  error    'next' is defined but never used           no-unused-vars
      16:3   warning  Unexpected console statement               no-console
    
    /home/alex/code-review/PCR-9290/routes/users.js
      10:9   error  A space is required after '{'                        object-curly-spacing
      10:12  error  A space is required before '}'                       object-curly-spacing
      11:7   error  'user' is never reassigned. Use 'const' instead      prefer-const
      11:25  error  Expected parentheses around arrow function argument  arrow-parens
      11:33  error  Unexpected dangling '_' in '_id'                     no-underscore-dangle
    
    ✖ 10 problems (8 errors, 2 warnings)
      6 errors and 0 warnings potentially fixable with the `--fix` option.
    ```

3) package.json: `"start": "app.js",` --> `"start": "node app.js",`

4) На фронтенде возникает ошибка при удалении карточки.

    ```text
    Uncaught TypeError: Cannot read property 'parentNode' of null
        at t.S [as openImageCallback] (main.c441beb49152e008eeed.js?6b8f37e689536e6385d7:1)
        at t.value (main.c441beb49152e008eeed.js?6b8f37e689536e6385d7:1)
    ```

#### Можно лучше

1) Есть один важный момент, на который хотелось бы обратить внимание. В какой-то момент так стали делать все. Формально, это не причина для возврата на доработку, но кажется это не правильно. Вот о чём речь:
   
   ```javascript
   const usersDB = require('../data/users');
   
   // В лучем случае в работах можно увидеть что-то такое
   const fs = require('fs');
   const path = require('path');
   const users = JSON.parse(fs.readFileSync(path.join(__dirname, '../data/users.json'), { encoding: 'utf8' }));
   ```
   
   Проблема тут в том, что мы читаем пользователей один раз при старте сервиса АПИ. И даже если поместить эту строку внутрь `users.get('/:id', (req, res) => { ... })` ни чего не изменится т.к. у `require` есть кеш. Вряд ли необходимость перезапускать АПИ при каждом изменении данных - хороший юзкейс. Конечно кеш можно почистить, но это скорее костыль, чем хорошее решение. (Документация: https://nodejs.org/api/modules.html#modules_require_cache)
   
   Предлагаю подумать над этим. А если не получится то я подскажу решение.


Напоминаю о необходимости фиксов по замечаниям с пометкой "Надо исправить".

2020-01-23 21:05 UTC, zhukovalexey76 commented on package.json
> +    "start": "app.js",
Надо исправить: `"start": "app.js",` --> `"start": "node app.js",`

2020-01-23 21:05 UTC, zhukovalexey76 commented on routes/users.js
> +    res.statusCode = 400;
Надо исправить: Not Found это 404
https://developer.mozilla.org/ru/docs/Web/HTTP/Status/404

2020-01-23 21:05 UTC, zhukovalexey76 commented on routes/users.js
> +  res.send(users);
Надо исправить: `userS` --> `user`

2020-01-23 21:05 UTC, zhukovalexey76 commented on routes/users.js
> +  let user = users.find(item => item._id === id._id);
Можно лучше: Как то тут напутано. id это вообще объект. Что если так:

```javascript
router.get('/users/:id', (req, res) => {
  const { id } = req.params;
  let user = users.find(item => item._id === id);
  // .....
```

2020-01-24 07:12 UTC, villigo commented
По 4-му пункту. На данный момент я так и не смог реализовать удаление карточки без данной ошибки. Тут мне нужна помощь.

2020-01-24 12:45 UTC, zhukovalexey76 commented
Помощь уже в пути (передал запрос команде наставников). 

Можно лучше: да верно. Вы можете убедиться в этом запустив апи и удалив или переименовав файлы с данными. Всё продолжет работать как работало.

2020-01-25 07:41 UTC, villigo commented
Исправлены ошибки.
Пункт "Можно лучше" не реализовал. Прошу показать правильный вариант.

2020-01-25 22:06 UTC, zhukovalexey76 approved these changes
Принято!

Поговорим о чтении файлов.

```javascript
// Как я уже писал обычно делают так
const usersDB = require('../data/users');

// Или в лучшем случае так
const users = JSON.parse(fs.readFileSync(path.join(__dirname, '../data/users.json'), { encoding: 'utf8' }));
```

Вариант с `fs.readFileSync` уже лучше, но еще не идеален, т.к. не учитывает наличие возможных ошибок при парсинге JSON и readFileSync - это синхронная ф-я, блокирующая выполнение остального кода до тех пор пока файл не будет прочитан.

Асинхронный вариант. Раньше у нас был только `readFile` с колбэками. Потом появился `promisify` и мы смогли делать так:

```javascript
const {promisify} = require('util');
const fs = require('fs');
const readFileAsync = promisify(fs.readFile);

readFileAsync(filePath, {encoding: 'utf8'}).then(() => {}).catch(() => {})

// Кстаии, если не указать {encoding: 'utf8'} то будет Buffer вместо строки, который потом не явно преобразуется в строку при JSON.parse. В итоге всё будет работать так же, но выглядеть менее очевидно.
```

Относительно недавно fs появились полноценные промисы. Так что теперь можно ни чего не костылить. А еще, у нас уже давно есть `async` и `await`. Это просто синтаксический сахар для промисов, но код выглядит существенно проще.

Вот пример реализации с промисами (`require('fs').promises`): https://pastebin.com/gW0T2cPV

А вот хороший скринкаст по теме: https://learn.javascript.ru/screencast/nodejs#nodejs-fs-fs

2020-01-25 22:06 UTC, zhukovalexey76 commented on routes/users.js
> +  const id = req.params;
Можно лучше: Эту штуку кажется уже отмечал. Она вводит в заблуждение, по тому что это не ID а объект params. Что-то вроде этого `{id: 'какой-то айдишник'}`. Врезультате ниже по коду получается еще более не понятная штука. Тут нужно было применить фишку ES6 назуваемую "деструктуризация".
[https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta](https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta)

2020-01-25 22:06 UTC, zhukovalexey76 commented on routes/users.js
> +  const user = users.find((item) => item._id === id.id);
```javascript
const { id } = req.params; // та самая деструктуризация. теперь тут строка а не объект
const user = users.find((item) => item._id === id);
```

2020-01-25 22:06 UTC, zhukovalexey76 commented on routes/users.js
> +    res.send({ message: 'Нет пользователя с таким id' });
еще можно так `res.status(404).json({ message: 'not found message.....' })`

2020-01-26 07:19 UTC, villigo commented on routes/users.js
> +  const id = req.params;
Дело в том, что я пытался использовать деструктуризацию с самого начала, но при таком подходе получал в переменную undefined. Поэтому от неё отказался.

2020-01-26 07:26 UTC, villigo commented on routes/users.js
> +  const id = req.params;
Странно. Попробовал сейчас. Всё ок )

2020-01-26 07:43 UTC, villigo commented on routes/users.js
> +  const id = req.params;
Пример с асинхронным чтением файла - супер!

2020-02-03 18:07 UTC, merged